apiVersion: apps/v1
kind: Deployment
metadata:
  name: knh-deployment
  namespace: monitoring
  labels:
    app: knc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: knc
  template:
    metadata:
      labels:
        app: knc
    spec:
      serviceAccountName: endpoints-reader-sa
      containers:
      - name: knc
        image: knc:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONTAINER_PORT
            value: "8080"
          - name: NAMESPACE
            value: monitoring
          - name: SERVICE_NAME
            value: svc-cluster-health-check          
          - name: SANITY_CHECK_URL
            value: "https://www.google.com"
          - name: LOG_LEVEL
            value: "trace"
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName            
          - name: PEER_STATUS_URL
            value: "http://192.168.1.102:8082"
          - name: CLUSTER_STATUS_URL
            value: "http://192.168.1.102:8082"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-cluster-health-check
  namespace: monitoring
spec:
  selector:
    app: knc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: endpoints-reader-sa
  namespace: monitoring
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: endpoints-reader-r
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: endpoints-reader-rb
subjects:
- kind: ServiceAccount
  name: endpoints-reader-sa # Name is case sensitive
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: endpoints-reader-r
  apiGroup: rbac.authorization.k8s.io  